# Generated by Django 5.1.3 on 2025-03-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reporting_manager',
            new_name='Allcate_Reporting_Manager',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date_of_joining',
            new_name='Date_of_joining',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mobile',
            new_name='Mobile_Number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='Set_password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='dept',
            new_name='select_dept',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='select_role',
        ),
    ]
